# Generated by Django 4.2.26 on 2025-11-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoFlexionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('numero', models.CharField(choices=[('Singular', 'Singular'), ('Plural', 'Plural')], max_length=10)),
                ('pessoa', models.CharField(choices=[('1a', '1a'), ('2a', '2a'), ('3a', '3a'), ('N/A', 'N/A')], default='N/A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('numero', models.CharField(choices=[('Singular', 'Singular'), ('Plural', 'Plural')], max_length=10)),
                ('pessoa', models.CharField(choices=[('1a', '1a'), ('2a', '2a'), ('3a', '3a'), ('N/A', 'N/A')], default='N/A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Verbal', 'Verbal'), ('Nominal', 'Nominal')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_exemplo', models.CharField(max_length=255)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concordancia.elementoflexionado')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concordancia.nucleo')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concordancia.regra')),
            ],
        ),
    ]
